- name: test my new module
  hosts: ispall
  gather_facts: no
  collections:
    - freedge.protect
  vars:
    credentials:
      username: leuser
      password: lepass
      serveraddress: lese
      command: ["bash", "mock.sh"]

  tasks:
    - name: configure script
      register: oldscript
      delegate_to: localhost
      configure_script:
        credentials: "{{ credentials }}"
        script: toto
        server: isp123
        content: "{{lookup('file', 'lescript')}}"
    - debug:
        msg: "Found difference: {{oldscript.lediff}}"

    - name: configure administrative schedule
      delegate_to: localhost
      configure_schedule:
        credentials: "{{ credentials }}"
        server: isp124
        schedule:
        - name: CHANGE_AAAAAAAAAAAAAAA
          command: update admin *
        - name: N1234_FULL
          command: run n1234_ndmp full
        
    - name: configure client schedule
      delegate_to: localhost
      configure_client_schedule:
        credentials: "{{ credentials }}"
        server: isp126
        schedule:
        - domain: VM
          name: BATCH
          options: '-vmbackuptype=fullvm -asnodename=AS -mode=ifi -domain.vmfull="Schedule-Tag"'

    # - name: configure path
    #   delegate_to: localhost
    #   configure_schedule:
    #     credentials: "{{ credentials }}"
    #     server: isp124
    #     schedule:
    #     - name: CHANGE_AAAAAAAAAAAAAAA
    #       command: update admin *
    #     - name: N1234_FULL
    #       command: run n1234_ndmp full
    
